# Generated by Django 2.0.5 on 2018-11-09 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image')),
                ('profile_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('nid', models.IntegerField()),
                ('is_owner', models.BooleanField(default=False)),
                ('phone', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Area')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.District')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Division')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Division'),
        ),
        migrations.AddField(
            model_name='area',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.District'),
        ),
    ]
