# Generated by Django 2.0.5 on 2018-12-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='profile_image')),
                ('daily', models.BooleanField()),
                ('weekly', models.BooleanField()),
                ('monthly', models.BooleanField()),
                ('is_available', models.BooleanField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.Profile')),
            ],
        ),
    ]
